spring.application.name=observability-test
management.endpoints.web.exposure.include=health,metrics
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/visitors
spring.datasource.username=myuser
spring.datasource.password=myuserpassword
logging.level.org.hibernate.SQL=INFO
spring.kafka.bootstrap-servers=localhost:9092