receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: myuser
    password: ${env:POSTGRESQL_PASSWORD}
    databases:
      - visitors
    collection_interval: 10s
    tls:
      insecure: true
  kafkametrics:
    brokers: [kafka:19092]
    protocol_version: 3.0.0
    scrapers: [brokers, topics, consumers]
    collection_interval: 10s

processors:
  resourcedetection:
    detectors: [ env, system ]
  batch:
  resource:
    attributes:
      - key: deployment.environment
        value: "local"
        action: upsert

exporters:
  otlp:
    endpoint: otel-lgtm:4317
    tls:
      insecure: true
  debug:
    verbosity: basic

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  telemetry:
    logs:
      level: "info"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp, postgresql, kafkametrics]
      processors: [batch, resource]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp, debug]
