receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  mysql:
    endpoint: mysql:3306
    password: ${env:MYSQL_PASSWORD}
    collection_interval: 10s
    initial_delay: 1s
    statement_events:
      digest_text_limit: 120
      time_limit: 24h
      limit: 250

processors:
  resourcedetection:
    detectors: [ env, system ]
  cumulativetodelta:
  batch:
  resource:
    attributes:
      - key: deployment.environment
        value: "local"
        action: upsert

exporters:
  otlp:
    endpoint: otel-lgtm:4317
    tls:
      insecure: true
  debug:
    verbosity: basic

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  telemetry:
    logs:
      level: "info"
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp, mysql]
      processors: [cumulativetodelta, batch, resource]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp, debug]