@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Container diagram for Observability Demo System

Person(user, User, "A user of the observability system")

System_Boundary(c1, "Observability Demo") {
    Container(backend_api, "API Application", "Java, Spring, Docker Container", "Provides Internet banking functionality via API")
    Container(otel_collection, "Open Telemetry Collector", "Docker Container", "Provides Internet banking functionality via API")
}

System_Ext(observability_backend, "Observability Backend", "Stores logs, traces, metrics and allows querying and viewing")

Rel(user, backend_api, "Uses", "HTTPS")

Rel_Neighbor(backend_api, otel_collection, "Uses", "OTLP")
Rel_Neighbor(otel_collection, observability_backend, "Uses", "OTLP")
@enduml