@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Container diagram for Observability Demo System

Person(user, User, "A user of the observability system")

System_Boundary(c1, "Observability Demo") {
    Container(observability_greeting, "Observability Greeting Application", "Java, Spring, Docker Container", "Provides Internet banking functionality via API")
    Container(observability_salutation, "Observability Salutation Application", "Java, Spring, Docker Container", "Provides Internet banking functionality via API")
    Container(otel_collection, "Open Telemetry Collector", "Docker Container", "Provides Internet banking functionality via API")
}

System_Ext(observability_backend, "OTEL LGTM", "Stores logs, traces, metrics and allows querying and viewing")
System_Ext(datadog, "DataDog", "Stores logs, traces, metrics and allows querying and viewing")
System_Ext(honeycomb, "Honeycomb", "Stores logs, traces, metrics and allows querying and viewing")

Rel(user, observability_greeting, "Uses", "HTTPS")
Rel_Neighbor(observability_greeting, observability_salutation, "Uses", "HTTPS")

Rel(observability_greeting, otel_collection, "Uses", "OTLP")
Rel(observability_salutation, otel_collection, "Uses", "OTLP")

Rel(otel_collection, datadog, "Uses", "OTLP")
Rel(otel_collection, observability_backend, "Uses", "OTLP")
Rel(otel_collection, honeycomb, "Uses", "OTLP")

@enduml